"""modficando tabla usuarios

Revision ID: 3ef7f2b396b6
Revises: 1b146198c037
Create Date: 2025-05-03 22:44:44.055071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef7f2b396b6'
down_revision = '1b146198c037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.Text(), nullable=False))
        batch_op.create_unique_constraint(None, ['correo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
