# Generated by Django 5.2.1 on 2025-05-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'platos',
                'ordering': ['nombre'],
            },
        ),
    ]
